### ISSUE TITLE
Build is broken since 0.6.0

### ISSUE THREAD

**Issue by SachaMorard** [edgee-cloud/edgee#143]
Binary releases and Crate publishing is broken.

Only Docker container push is okay<br><br>[https://github.com/edgee-cloud/edgee/actions/runs/12264000976](https://github.com/edgee-cloud/edgee/actions/runs/12264000976)<br>[https://github.com/edgee-cloud/edgee/actions/runs/12264000961](https://github.com/edgee-cloud/edgee/actions/runs/12264000961)

**Comment by alexcasalboni** [comment]
FYI the install.sh script is broken too sine the latest release doesn't have any binaries
