### ISSUE TITLE
Either HTTP or HTTPS is mandatory, but not both

### ISSUE THREAD

**Issue by SachaMorard** [edgee-cloud/edgee#35]
**Is your feature request related to a problem? Please describe.**

Edgee currently requires HTTP AND HTTPS configurations. 
Instead, a user must be able to configure Edgee to receive traffic only in HTTP, only in HTTPS, or both.

**Describe the solution you'd like**

Change the configuration to allow it
Change the `entrypoint::start()` method to launch either `web::start()` and/or `websecure::start()`

**Comment by spantheslayer** [comment]
Picked up this issue and working on it. As as first impression of the codebase what I understand is that the 
`src/entrypoint/web.rs` corresponds to HTTP and `src/entrypoint/websecure.rs` corresponds to HTTPS. 

Please correct me if I am wrong and also I believe the change needs to made here in `src/main.rs` 

 ```
tokio::select! {
    Err(err) = monitor::start() => error!(?err, "Monitor failed"),
    Err(err) = entrypoint::start() => error!(?err, "Entrypoint failed"),
}
```

**Comment by SachaMorard** [comment]
> Picked up this issue and working on it. As a first impression of the codebase what I understand is that the `src/entrypoint/web.rs` corresponds to HTTP and `src/entrypoint/websecure.rs` corresponds to HTTPS.
> 
> Please correct me if I am wrong.

Yeah, you're right!
