### ISSUE TITLE
Put edgee sdk in a dedicated crate

### ISSUE THREAD

**Issue by SachaMorard** [edgee-cloud/edgee#56]
The Edgee JS SDK is currently processed and rendered directly in this repo, but also in other repos.

It would make more sense to deport it to a dedicated crate, managed from the sdk repo itself.

**Comment by mikbry** [comment]
Yes, I think you should reorganize a little the code using crates (Rust) & packages (JS/Typescript) root directories. 
And add a private root package.json to handle workspaces.
edgee-react repo could be in packages and splitted to separate typing definitions, react/next in differents packages.
