### ISSUE TITLE
No UI on the open source version, or I missed something ?

### ISSUE THREAD

**Issue by jrouaix** [edgee-cloud/edgee#79]
Hello,

I don't have yet access to the tool (i'm on the waitlist), but wanted to test it.

Once ran, I did not really know anything about what was working or not, and didn't find any UI.

Is it a feature yet to open source ? is it something something you want to keep closed, or should I just seek more ?

Congrats for your product, can't wait to test it.

**Comment by SachaMorard** [comment]
Hello @jrouaix. You're right, there's no user interface for Edgee's OSS edition, only for the Enterprise edition (managed service).
We know it's a bit hard to explore Edgee OSS without guidance, and we are working hard to improve the OSS documentation soon. 
To tide you over, I invite you to join us on [Slack](https://www.edgee.cloud/slack) and send me the email you used to register on edgee.cloud, I'll take you off the waitlist.
