### ISSUE TITLE
Improve Debugging for Data Collection Calls

### ISSUE THREAD

**Issue by SachaMorard** [edgee-cloud/edgee#87]
**Description:**

Currently, the logging for data collection calls includes:

* Logging the Edgee payload:

  ```rust
  info!(target: "data_collection", payload = payload_json.as_str());
  ```
* Logging the result of the HTTP call to the data collection provider:

  ```rust
  info!(target: "data_collection", step = "response", provider = cfg.name, event = event_str, method = method_str, status = status_str, body = body_res_str);
  ```

While these logs provide useful information, they are mixed with other logs, making it difficult to read and debug. We need a better way to isolate and format these logs.

**Requirements:**

1. **Log Filtering:**
   * Implement an option to filter and display only the logs from the `data_collection` log target.
2. **Pretty Print Logs:**
   * Add a `--pretty` option to format the logs for better JSON readability.

**Tasks:**

1. **Log Filtering:**
   * Modify the logging configuration to support filtering by log target.
   * Ensure that when the filter is applied, only logs from the `data_collection` target are displayed.
2. **Pretty Print Logs:**
   * Implement a `--pretty` option that formats JSON logs for better readability.
   * Ensure that this option can be toggled on and off.

**Additional Context:**

Improving the readability and filtering of logs will significantly enhance the debugging process for data collection calls. This will help developers quickly identify and resolve issues related to data collection.

**Example:**

```rust
// Example of pretty-printed JSON log
info!(target: "data_collection", payload = serde_json::to_string_pretty(&payload_json).unwrap().as_str());
```

**Comment by KokaKiwi** [comment]
Wouldn't it be better to follow the `RUST_LOG` convention (or something like `EDGEE_LOG`) for defining logging instead (or in combination) of putting that in the config file?

It would also allow using the full `tracing_subscriber::EnvFilter` filtering capabilities (which allows to filter by not only log level but also module, target, span and fields)
