### ISSUE TITLE
Make Data-Collection Component Calls Asynchronous

### ISSUE THREAD

**Issue by SachaMorard** [edgee-cloud/edgee#92]
**Description:**

The performance of the `components.rs` file is currently suboptimal due to synchronous calls to the data-collection components. To improve performance, we should make these calls asynchronous.

**Proposed Solutions:**

1. Use the `bindgen` with the `async` option:

   ```rust
   wasmtime::component::bindgen!({world: "data-collection", path: "wit/protocols.wit", async: true});
   ```

   This approach seems interesting, but it would require many changes in the way we instanciate the component. 
2. Spawn a Tokio async process at the beginning of the `~~init()~~` `send_data_collection()` function.

**Tasks:**

* Modify the `wasmtime::component::bindgen!` macro to include the `async: true` option.
* And/Or Refactor the `init()` function to spawn a Tokio async process if necessary.
* Ensure all component calls within `send_data_collection` are handled asynchronously.
* Test the changes to verify improved performance and correct functionality.

**Files Affected:**

* `src/proxy/compute/data_collection/components.rs`

**References:**

* Current implementation of `components.rs` and `wit/protocols.wit`.

**Comment by KokaKiwi** [comment]
> Spawn a Tokio async process at the beginning of the init() function.

I don't understand the goal here, the `proxy::compute::data_collection::components::init()` call is made at startup time of the program, before spinning up server&monitor, which is not really on the critical path of edgee (which is supposedly the path taken from a received request and the response being sent back to client)
Apart from a (maybe) faster startup time, we wouldn't gain much more from doing the `init()` call on another Tokio task i think.

**Comment by SachaMorard** [comment]
Sorry, I wasn't specific enough in my description. The second proposed solution concerns the `send_data_collection` function rather than \`init\`.
